/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package chandani_q1_student_crud;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Test
 */
public class NewJFrame extends javax.swing.JFrame {

    
    Connection cn;
    Statement st;
    ResultSet rs;
    String id,name,email,address;
    Date dob;
    
    int ans;
    
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        SrudentCrudjInternalFrame = new javax.swing.JInternalFrame();
        btnClear = new java.awt.Button();
        label5 = new java.awt.Label();
        label4 = new java.awt.Label();
        txtAddress = new java.awt.TextArea();
        label1 = new java.awt.Label();
        txtId = new java.awt.TextField();
        txtName = new java.awt.TextField();
        txtEmail = new java.awt.TextField();
        label3 = new java.awt.Label();
        btnInsert = new java.awt.Button();
        lblTitle = new java.awt.Label();
        txtDOB = new java.awt.TextField();
        btnFind = new java.awt.Button();
        label2 = new java.awt.Label();
        btnUpdate = new java.awt.Button();
        btnDelete = new java.awt.Button();
        StudentRetriveAlljInternalFrame = new javax.swing.JInternalFrame();
        btnLast = new java.awt.Button();
        lblTitle1 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        txtAddress1 = new java.awt.TextArea();
        label8 = new java.awt.Label();
        txtId1 = new java.awt.TextField();
        txtName1 = new java.awt.TextField();
        txtEmail1 = new java.awt.TextField();
        btnFirst = new java.awt.Button();
        label9 = new java.awt.Label();
        btnPrev = new java.awt.Button();
        txtDOB1 = new java.awt.TextField();
        btnNext = new java.awt.Button();
        label10 = new java.awt.Label();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuAllStudent = new javax.swing.JMenu();
        MenuCRUDStudent = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SrudentCrudjInternalFrame.setClosable(true);
        SrudentCrudjInternalFrame.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        SrudentCrudjInternalFrame.setResizable(true);
        SrudentCrudjInternalFrame.setAutoscrolls(true);
        SrudentCrudjInternalFrame.setPreferredSize(new java.awt.Dimension(500, 650));
        SrudentCrudjInternalFrame.setVisible(true);

        btnClear.setLabel("Clear");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });

        label5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label5.setText("Address : ");

        label4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label4.setText("DOB : ");

        label1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label1.setText("Student id : ");

        txtName.setName(""); // NOI18N

        label3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label3.setText("Email : ");

        btnInsert.setLabel("Insert");
        btnInsert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertMouseClicked(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTitle.setText("Student CRUD Operation");

        btnFind.setLabel("Find");
        btnFind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFindMouseClicked(evt);
            }
        });

        label2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label2.setText("Student Name : ");

        btnUpdate.setLabel("Update");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });

        btnDelete.setLabel("Delete");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SrudentCrudjInternalFrameLayout = new javax.swing.GroupLayout(SrudentCrudjInternalFrame.getContentPane());
        SrudentCrudjInternalFrame.getContentPane().setLayout(SrudentCrudjInternalFrameLayout);
        SrudentCrudjInternalFrameLayout.setHorizontalGroup(
            SrudentCrudjInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SrudentCrudjInternalFrameLayout.createSequentialGroup()
                .addGroup(SrudentCrudjInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SrudentCrudjInternalFrameLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SrudentCrudjInternalFrameLayout.createSequentialGroup()
                        .addGroup(SrudentCrudjInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SrudentCrudjInternalFrameLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SrudentCrudjInternalFrameLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(SrudentCrudjInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(SrudentCrudjInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SrudentCrudjInternalFrameLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(SrudentCrudjInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(SrudentCrudjInternalFrameLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        SrudentCrudjInternalFrameLayout.setVerticalGroup(
            SrudentCrudjInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SrudentCrudjInternalFrameLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SrudentCrudjInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SrudentCrudjInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SrudentCrudjInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SrudentCrudjInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SrudentCrudjInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(SrudentCrudjInternalFrameLayout.createSequentialGroup()
                        .addGroup(SrudentCrudjInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(SrudentCrudjInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SrudentCrudjInternalFrameLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SrudentCrudjInternalFrameLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(SrudentCrudjInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnClear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(249, 249, 249))
        );

        StudentRetriveAlljInternalFrame.setClosable(true);
        StudentRetriveAlljInternalFrame.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        StudentRetriveAlljInternalFrame.setPreferredSize(new java.awt.Dimension(500, 650));
        StudentRetriveAlljInternalFrame.setVisible(true);
        StudentRetriveAlljInternalFrame.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                StudentRetriveAlljInternalFrameInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                StudentRetriveAlljInternalFrameInternalFrameOpened(evt);
            }
        });

        btnLast.setLabel("Last");
        btnLast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLastMouseClicked(evt);
            }
        });

        lblTitle1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTitle1.setText("Student All Data");

        label6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label6.setText("Address : ");

        label7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label7.setText("DOB : ");

        label8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label8.setText("Student id : ");

        txtName1.setName(""); // NOI18N

        btnFirst.setLabel("First");
        btnFirst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFirstMouseClicked(evt);
            }
        });

        label9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label9.setText("Email : ");

        btnPrev.setLabel("Prev");
        btnPrev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrevMouseClicked(evt);
            }
        });

        btnNext.setLabel("Next");
        btnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextMouseClicked(evt);
            }
        });

        label10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label10.setText("Student Name : ");

        javax.swing.GroupLayout StudentRetriveAlljInternalFrameLayout = new javax.swing.GroupLayout(StudentRetriveAlljInternalFrame.getContentPane());
        StudentRetriveAlljInternalFrame.getContentPane().setLayout(StudentRetriveAlljInternalFrameLayout);
        StudentRetriveAlljInternalFrameLayout.setHorizontalGroup(
            StudentRetriveAlljInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentRetriveAlljInternalFrameLayout.createSequentialGroup()
                .addGroup(StudentRetriveAlljInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentRetriveAlljInternalFrameLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StudentRetriveAlljInternalFrameLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(StudentRetriveAlljInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(StudentRetriveAlljInternalFrameLayout.createSequentialGroup()
                                .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(StudentRetriveAlljInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(StudentRetriveAlljInternalFrameLayout.createSequentialGroup()
                                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(StudentRetriveAlljInternalFrameLayout.createSequentialGroup()
                                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDOB1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(StudentRetriveAlljInternalFrameLayout.createSequentialGroup()
                                    .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentRetriveAlljInternalFrameLayout.createSequentialGroup()
                                    .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentRetriveAlljInternalFrameLayout.createSequentialGroup()
                                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(47, 47, 47)
                                    .addComponent(txtId1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        StudentRetriveAlljInternalFrameLayout.setVerticalGroup(
            StudentRetriveAlljInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentRetriveAlljInternalFrameLayout.createSequentialGroup()
                .addGroup(StudentRetriveAlljInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(StudentRetriveAlljInternalFrameLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StudentRetriveAlljInternalFrameLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(StudentRetriveAlljInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(StudentRetriveAlljInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(StudentRetriveAlljInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(StudentRetriveAlljInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(StudentRetriveAlljInternalFrameLayout.createSequentialGroup()
                                .addComponent(txtDOB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(StudentRetriveAlljInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(StudentRetriveAlljInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(286, 286, 286))
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(SrudentCrudjInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StudentRetriveAlljInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(StudentRetriveAlljInternalFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                    .addComponent(SrudentCrudjInternalFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE))
                .addGap(111, 111, 111))
        );
        jDesktopPane1.setLayer(SrudentCrudjInternalFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(StudentRetriveAlljInternalFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);

        MenuAllStudent.setText("Display All Student");
        MenuAllStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuAllStudentMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuAllStudent);

        MenuCRUDStudent.setText("CRUD Student");
        MenuCRUDStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuCRUDStudentMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuCRUDStudent);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuAllStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuAllStudentMouseClicked
//        SrudentCrudjInternalFrame.hide();
        StudentRetriveAlljInternalFrame.show();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/chandani_java?zeroDateTimeBehavior=convertToNull", "root", "");
            Statement st = cn.createStatement();
            rs = st.executeQuery("select * from q1_student");
            rs.next();
            txtId.setText(rs.getString("sid"));
            txtName.setText(rs.getString("name"));
            txtEmail.setText(rs.getString("email"));
            txtDOB.setText(rs.getString("dob"));
            txtAddress.setText(rs.getString("address"));
        }catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        }catch(SQLException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_MenuAllStudentMouseClicked

    private void MenuCRUDStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuCRUDStudentMouseClicked
//        StudentRetriveAll frame = new StudentRetriveAll();
//        frame.show();
//        StudentRetriveAlljInternalFrame.hide();
        SrudentCrudjInternalFrame.show();
    }//GEN-LAST:event_MenuCRUDStudentMouseClicked

    
    private void clear(){
        txtId.setText("");
        txtName.setText("");
        txtEmail.setText("");
        txtDOB.setText("");
        txtAddress.setText("");
    }
    
    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        clear();
    }//GEN-LAST:event_btnClearMouseClicked

    private void btnInsertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertMouseClicked

        try {
            name = txtName.getText();
            email = txtEmail.getText();
            dob = Date.valueOf(txtDOB.getText());
            address = txtAddress.getText();

            if(name.equals("") || email.equals("") || dob.equals("") || address.equals("")){
                JOptionPane.showMessageDialog(this, "Please enter all details...");
                System.out.println("Please enter all details...");
            }
            else{
                Class.forName("com.mysql.jdbc.Driver");
                cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/chandani_java?zeroDateTimeBehavior=convertToNull","root","");
                st = cn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);

                ans = st.executeUpdate("insert into q1_student(name,email,dob,address) values('"+name+"','"+email+"','"+dob+"','"+address+"')");
                if(ans > 0){
                    JOptionPane.showMessageDialog(this, "Inserted Successfully");
                }
                else{
                    JOptionPane.showMessageDialog(this, "Not Inserted");
                }

                //                rs = st.executeQuery("select * from q1_student");
                //                rs.moveToInsertRow();
                //                rs.updateString("name", name);
                //                rs.updateString("email", email);
                //                rs.updateDate("dob", dob);
                //                rs.updateString("address", address);
                //                rs.insertRow();
            }
        }
        catch (ClassNotFoundException ex) {
            System.out.println(ex.getException());
        }
        catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_btnInsertMouseClicked

    private void btnFindMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFindMouseClicked
        try {
            id = txtId.getText();

            Class.forName("com.mysql.jdbc.Driver");
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/chandani_java?zeroDateTimeBehavior=convertToNull","root","");
            st = cn.createStatement();
            rs = st.executeQuery("select count(*) from q1_student where sid = "+id+"");
            rs.next();
            if(rs.getInt(1) >= 1){
                rs = st.executeQuery("select * from q1_student where sid = "+id);
                rs.next();
                txtId.setText(rs.getString("sid"));
                txtName.setText(rs.getString("name"));
                txtEmail.setText(rs.getString("email"));
                txtDOB.setText(rs.getDate("dob").toString());
                txtAddress.setText(rs.getString("address"));
            }
            else{
                System.out.println("Student id Not Found");
                clear();
                JOptionPane.showMessageDialog(this, "Student id Not Found....");
            }

        }
        catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        }
        catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnFindMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        try {
            id = txtId.getText();
            name = txtName.getText();
            email = txtEmail.getText();
            dob = Date.valueOf(txtDOB.getText());
            address = txtAddress.getText();

            if(id.equals("") || name.equals("") || email.equals("") || dob.equals("") || address.equals("")){
                System.out.println("Please enter all details...");
            }
            else{
                Class.forName("com.mysql.jdbc.Driver");
                cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/chandani_java?zeroDateTimeBehavior=convertToNull","root","");
                st = cn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);

                int ans = st.executeUpdate("update q1_student set name='"+name+"',email='"+email+"',dob='"+dob+"',address='"+address+"' where sid="+id+"");
                if(ans > 0){
                    System.out.println("Updated");
                    clear();
                    JOptionPane.showMessageDialog(this, "Updated Successfully");
                }
                else{
                    System.out.println("Not Updated");
                    clear();
                    JOptionPane.showMessageDialog(this, " Not Updated");
                }

                //                ResultSet rs = st.executeQuery("select * from q1_student");
                //                while(rs.next()){
                    //                    if((rs.getString("sid")).equals(id)){
                        //                        rs.updateString("name", name);
                        //                        rs.updateString("email", email);
                        //                        rs.updateDate("dob", dob);
                        //                        rs.updateString("address", address);
                        //                        rs.updateRow();
                        //                    }
                    //                }
            }

        }
        catch (ClassNotFoundException ex) {
            System.out.println(ex.getException());
        }
        catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        try {
            id = txtId.getText();
            if(id.equals("")){
                JOptionPane.showMessageDialog(this, "Please enter Uid  to delete");
                System.out.println("Please enter Uid  to delete");
            }
            else{

                Class.forName("com.mysql.jdbc.Driver");
                cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/chandani_java?zeroDateTimeBehavior=convertToNull","root","");
                st = cn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);

                int ans = st.executeUpdate("delete from q1_student where sid = "+id+"");

                if(ans > 0){
                    System.out.println("Deleted");
                    clear();
                    JOptionPane.showMessageDialog(this, "Deleted Successfully");
                }
                else{
                    System.out.println("Not Deleted");
                    clear();
                    JOptionPane.showMessageDialog(this, "Deleted Successfully");
                }

                //                ResultSet rs = st.executeQuery("select * from q1_student");
                //                while(rs.next()){
                    //                    if((rs.getString("sid")).equals(id)){
                        //                        rs.deleteRow();
                        //                    }
                    //                }

            }

        }
        catch (ClassNotFoundException ex) {
            System.out.println(ex.getException());
        }
        catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnLastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLastMouseClicked
        try {
            rs.last();
            txtId.setText(rs.getString("sid"));
            txtName.setText(rs.getString("name"));
            txtDOB.setText(rs.getString("dob"));
            txtEmail.setText(rs.getString("email"));
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnLastMouseClicked

    private void btnFirstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFirstMouseClicked
        try {
            rs.first();
            txtId.setText(rs.getString("sid"));
            txtName.setText(rs.getString("name"));
            txtDOB.setText(rs.getString("dob"));
            txtEmail.setText(rs.getString("email"));
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnFirstMouseClicked

    private void btnPrevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrevMouseClicked
        try {
            rs.previous();
            txtId.setText(rs.getString("sid"));
            txtName.setText(rs.getString("name"));
            txtDOB.setText(rs.getString("dob"));
            txtEmail.setText(rs.getString("email"));
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnPrevMouseClicked

    private void btnNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextMouseClicked
        try {
            rs.next();
            txtId.setText(rs.getString("sid"));
            txtName.setText(rs.getString("name"));
            txtDOB.setText(rs.getString("dob"));
            txtEmail.setText(rs.getString("email"));
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnNextMouseClicked

    private void StudentRetriveAlljInternalFrameInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_StudentRetriveAlljInternalFrameInternalFrameActivated
        try {
            Class.forName("com.mysql.jdbc.Driver");
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/chandani_java?zeroDateTimeBehavior=convertToNull", "root", "");
            Statement st = cn.createStatement();
            rs = st.executeQuery("select * from q1_student");
            rs.next();
            txtId.setText(rs.getString("sid"));
            txtName.setText(rs.getString("name"));
            txtEmail.setText(rs.getString("email"));
            txtDOB.setText(rs.getString("dob"));
            txtAddress.setText(rs.getString("address"));
        }catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        }catch(SQLException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_StudentRetriveAlljInternalFrameInternalFrameActivated

    private void StudentRetriveAlljInternalFrameInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_StudentRetriveAlljInternalFrameInternalFrameOpened
        StudentRetriveAlljInternalFrameInternalFrameActivated(evt);
    }//GEN-LAST:event_StudentRetriveAlljInternalFrameInternalFrameOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAllStudent;
    private javax.swing.JMenu MenuCRUDStudent;
    private javax.swing.JInternalFrame SrudentCrudjInternalFrame;
    private javax.swing.JInternalFrame StudentRetriveAlljInternalFrame;
    private java.awt.Button btnClear;
    private java.awt.Button btnDelete;
    private java.awt.Button btnFind;
    private java.awt.Button btnFirst;
    private java.awt.Button btnInsert;
    private java.awt.Button btnLast;
    private java.awt.Button btnNext;
    private java.awt.Button btnPrev;
    private java.awt.Button btnUpdate;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.Label lblTitle;
    private java.awt.Label lblTitle1;
    private java.awt.TextArea txtAddress;
    private java.awt.TextArea txtAddress1;
    private java.awt.TextField txtDOB;
    private java.awt.TextField txtDOB1;
    private java.awt.TextField txtEmail;
    private java.awt.TextField txtEmail1;
    private java.awt.TextField txtId;
    private java.awt.TextField txtId1;
    private java.awt.TextField txtName;
    private java.awt.TextField txtName1;
    // End of variables declaration//GEN-END:variables
}
